-- 코드를 입력하세요
SELECT  APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
LEFT JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
LEFT JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE APNT_YMD like '2022-04-13%'
    AND A.mcdp_cd = 'CS'
    AND APNT_CNCL_YN = 'N'
ORDER BY 6