-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') as TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BEtWEEN_DIST),2),'km') as AVERAGE_DISTANCE
FROM subway_distance
GROUP BY 1
ORDER BY SUM(D_BETWEEN_DIST) DESC