-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(price) AS TOTAL_SALES
FROM USED_GOODS_BOARD GB
JOIN USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
WHERE status = 'DONE'
GROUP BY 1, 2
HAVING SUM(price) >= 700000
ORDER BY 3