-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) as YEAR,
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ecoli_data D
     WHERE YEAR(D.DIFFERENTIATION_DATE) = YEAR(E.DIFFERENTIATION_DATE))
      - size_of_colony AS YEAR_DEV,
    ID
FROM ecoli_data E
ORDER BY 1,2